/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TripsNewTripRouteImport } from './routes/trips.new-trip'
import { Route as TripsIdRouteImport } from './routes/trips.$id'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TripsRoute,
} as any)
const TripsNewTripRoute = TripsNewTripRouteImport.update({
  id: '/new-trip',
  path: '/new-trip',
  getParentRoute: () => TripsRoute,
} as any)
const TripsIdRoute = TripsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TripsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trips': typeof TripsRouteWithChildren
  '/trips/$id': typeof TripsIdRoute
  '/trips/new-trip': typeof TripsNewTripRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trips/$id': typeof TripsIdRoute
  '/trips/new-trip': typeof TripsNewTripRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trips': typeof TripsRouteWithChildren
  '/trips/$id': typeof TripsIdRoute
  '/trips/new-trip': typeof TripsNewTripRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/trips'
    | '/trips/$id'
    | '/trips/new-trip'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/trips/$id' | '/trips/new-trip' | '/trips'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/trips'
    | '/trips/$id'
    | '/trips/new-trip'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TripsRoute: typeof TripsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof TripsRoute
    }
    '/trips/new-trip': {
      id: '/trips/new-trip'
      path: '/new-trip'
      fullPath: '/trips/new-trip'
      preLoaderRoute: typeof TripsNewTripRouteImport
      parentRoute: typeof TripsRoute
    }
    '/trips/$id': {
      id: '/trips/$id'
      path: '/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof TripsIdRouteImport
      parentRoute: typeof TripsRoute
    }
  }
}

interface TripsRouteChildren {
  TripsIdRoute: typeof TripsIdRoute
  TripsNewTripRoute: typeof TripsNewTripRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

const TripsRouteChildren: TripsRouteChildren = {
  TripsIdRoute: TripsIdRoute,
  TripsNewTripRoute: TripsNewTripRoute,
  TripsIndexRoute: TripsIndexRoute,
}

const TripsRouteWithChildren = TripsRoute._addFileChildren(TripsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TripsRoute: TripsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
